version: '3'

services:

    # nginx
    nginx-service:
        image: nginx:stable-alpine
        container_name: nginx-container
        restart: always
        #ports:
        #    - "8081:80"
        volumes:
            - ./app:/var/www/project
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php74-service
            - mariadb-service
            - node-service
        labels:
          traefik.enable: true
          traefik.http.routers.pinha-http.rule: "Host(`xn--pia-8ma.org`) || Host(`pinha.hydra-net.es`)"
          traefik.http.routers.pinha-http.entrypoints: web
          traefik.http.routers.pinha-http.middlewares: pinha-https
          traefik.http.middlewares.pinha-https.redirectscheme.scheme: https
          traefik.http.middlewares.pinha-https.redirectscheme.permanent: true
          traefik.http.routers.pinha-https.entrypoints: websecure
          traefik.http.routers.pinha-https.rule: "Host(`xn--pia-8ma.org`) || Host(`pinha.hydra-net.es`)"
          traefik.http.services.pinha-https.loadbalancer.server.port: 80
          traefik.http.routers.pinha-https.tls: true
          traefik.http.routers.pinha-https.tls.certresolver: cerbot

        networks:
            - pinha
            - traefik

    # php
    php74-service:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: php74-container
        restart: always
        volumes:
            - ./app:/var/www/project
        networks:
            - pinha

    # mysql
    mariadb-service:
        image: mariadb:10.5.8
        container_name: mariadb-container
        ports:
            - "3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
            - ./database:/docker-entrypoint-initdb.d
        restart: always 
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        environment:
            MYSQL_DATABASE: database
            MYSQL_USER: user
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
        networks:
            - pinha

    #phpmyadmin
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:5.0.1
        restart: always
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: mariadb
        #ports:
            #- "8080:80"
        networks:
            - pinha
    # node
    node-service:
        build:
            context: .
            dockerfile: ./node/Dockerfile
        container_name: node-container
        restart: always
        volumes:
            - ./app:/var/www/project
        depends_on: 
            - php74-service
        stdin_open: true
        tty: true
        networks:
            - pinha

networks:
    pinha:
    traefik:
       external:
          name: traefik_default