<?php

namespace ContainerWulojqO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDepartmentsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Models\Departments\Departments' shared autowired service.
     *
     * @return \App\Controller\Models\Departments\Departments
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Models/Departments/Departments.php';

        $container->services['App\\Controller\\Models\\Departments\\Departments'] = $instance = new \App\Controller\Models\Departments\Departments();

        $instance->setContainer(($container->privates['.service_locator.5nX7ca3'] ?? $container->load('get_ServiceLocator_5nX7ca3Service'))->withContext('App\\Controller\\Models\\Departments\\Departments', $container));

        return $instance;
    }
}
