<?php

namespace ContainerWulojqO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmailControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\EmailController' shared autowired service.
     *
     * @return \App\Controller\EmailController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/EmailController.php';

        return $container->services['App\\Controller\\EmailController'] = new \App\Controller\EmailController();
    }
}
