<?php

namespace ContainerWulojqO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTeamsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Models\Teams\Teams' shared autowired service.
     *
     * @return \App\Controller\Models\Teams\Teams
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Models/Teams/Teams.php';

        $container->services['App\\Controller\\Models\\Teams\\Teams'] = $instance = new \App\Controller\Models\Teams\Teams();

        $instance->setContainer(($container->privates['.service_locator.5nX7ca3'] ?? $container->load('get_ServiceLocator_5nX7ca3Service'))->withContext('App\\Controller\\Models\\Teams\\Teams', $container));

        return $instance;
    }
}
